Repository JonathanRangelB/YOOX-serverless, pull requests merged in 2025-04, with the labels that each got.

#63 Crear prestamo refinanciamiento
  src/general-data-requests/getLoansRefinance.ts
  src/general-data-requests/transactions/customer/updateCustomer.ts
  src/general-data-requests/transactions/loan/registerNewLoan.ts
  src/general-data-requests/transactions/refinancing/registerNewRefinancing.ts
  src/general-data-requests/transactions/reporting/registerSnapshotRealInvestmentReport.ts
  src/general-data-requests/utils/querySearchLoanToRefinance.ts
  src/helpers/table-schemas.ts
  src/loan-requests/loans/registerUpdateLoanRequest.ts
  src/loan-requests/schemas/propertiesForLoanRequest.schema.ts
  src/loan-requests/types/SPInsertNewLoanRequest.ts
  src/loan-requests/utils/generateNewLoanRequestTable.ts
  src/loan-requests/utils/validateData.ts
Labels: enhancement

#65 feat: mejora endpoint curp y telefonos
  src/loan-requests/loans/registerUpdateLoanRequest.ts
  src/loan-requests/updateLoan.ts
  src/loan-requests/utils/validateData.ts
  src/validators/schemas/personaCURP.schema.ts
  src/validators/schemas/personaTelefono.schema.ts
  src/validators/types/DatosBusqueda.interface.ts
  src/validators/utils/querySearchData.ts
  src/validators/validateCURP.ts
  src/validators/validatePhones.ts
Labels: enhancement

#67 Mejora validar iddomicilios
  src/loan-requests/schemas/propertiesForLoanRequest.schema.ts
  src/loan-requests/utils/validateData.ts
Labels: enhancement

#68 chore: aplicando migracion
  .prettierrc
  biome.json
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/payments/registerPayment.ts
Labels: enhancement

#69 Agregados campos para datos de refinanciamiento
  serverless.yml
  src/general-data-requests/getRequestDetail.ts
  src/general-data-requests/utils/querySearchRequestDetail.ts
  src/loan-requests/viewLoan.ts
Labels: enhancement

#70 Arreglo en query de busqueda de telefonos aval/cliente
  src/validators/utils/querySearchData.ts
Labels: bug

#71 fix: arreglo en query de busqueda refinaciamiento
  src/general-data-requests/getLoansRefinance.ts
  src/general-data-requests/transactions/refinancing/registerNewRefinancing.ts
  src/general-data-requests/utils/querySearchLoanToRefinance.ts
  src/loan-requests/utils/validateData.ts
Labels: bug

#72 Arreglo endpoints validadores curp/telefono
  src/validators/schemas/personaCURP.schema.ts
  src/validators/schemas/personaTelefono.schema.ts
Labels: bug

#73 Ajustes detalles
  src/address/transactions/registerNewAddress.ts
  src/customerFiles/getFile.ts
  src/customerFiles/types/fileData.ts
  src/general-data-requests/getAddress.ts
  src/general-data-requests/getLoansRefinance.ts
  src/general-data-requests/transactions/address/registerNewAddress.ts
  src/general-data-requests/transactions/address/updateAddress.ts
  src/general-data-requests/transactions/customer/registerNewCustomer.ts
  src/general-data-requests/transactions/customer/updateCustomer.ts
  src/general-data-requests/transactions/endorsement/registerNewEndorsement.ts
  src/general-data-requests/transactions/endorsement/updateEndorsement.ts
  src/general-data-requests/transactions/loan/registerNewLoan.ts
  src/general-data-requests/transactions/refinancing/registerNewRefinancing.ts
  src/general-data-requests/transactions/reporting/registerSnapshotRealInvestmentReport.ts
  src/general-data-requests/types/customerRequest.ts
  src/general-data-requests/types/endorsmentRequest.ts
  src/general-data-requests/types/genericBDRequest.ts
  src/general-data-requests/types/getCustomer.interface.ts
  src/general-data-requests/types/getRequest.interface.ts
  src/helpers/table-schemas.ts
  src/helpers/utils.ts
  src/interfaces/customer-interface.ts
  src/interfaces/endorsement-interface.ts
  src/interfaces/loan-interface.ts
  src/loan-requests/loans/registerNewLoanRequest.ts
  src/loan-requests/loans/registerUpdateLoanRequest.ts
  src/loan-requests/types/SPInsertNewLoanRequest.ts
  src/loan-requests/types/loanRequest.ts
  src/loan-requests/types/validateLoanResponse.ts
  src/loan-requests/utils/validateData.ts
  src/payments/getPagosAdelantadosPermitidos.ts
  src/payments/registerPayment.ts
  src/payments/types/pagos.ts
  src/user-service/login.ts
  src/user-service/types/user-service.ts
  src/user-service/validateCredentials.ts
Labels: Refactor

#74 fix: filtro de listado de solicitudes de prestamo
  src/loan-requests/utils/querySearchLoanList.ts
  src/loan-requests/viewLoanList.ts
Labels: bug

#75 feat: nuevo endpoint busqueda de avales
  serverless.yml
  src/general-data-requests/getGuarantor.ts
  src/general-data-requests/schemas/guarantor.schema.ts
  src/general-data-requests/types/getGuarantor.interface.ts
  src/general-data-requests/utils/querySearchGuarantor.ts
Labels: enhancement
